// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: listentogether.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message envelope with type and payload
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Compressed    bool                   `protobuf:"varint,3,opt,name=compressed,proto3" json:"compressed,omitempty"` // Indicates if payload is gzip compressed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_listentogether_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

// Track information
type TrackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	SuggestedBy   string                 `protobuf:"bytes,7,opt,name=suggested_by,json=suggestedBy,proto3" json:"suggested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfo) Reset() {
	*x = TrackInfo{}
	mi := &file_listentogether_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfo) ProtoMessage() {}

func (x *TrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfo.ProtoReflect.Descriptor instead.
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{1}
}

func (x *TrackInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrackInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrackInfo) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *TrackInfo) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *TrackInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TrackInfo) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *TrackInfo) GetSuggestedBy() string {
	if x != nil {
		return x.SuggestedBy
	}
	return ""
}

// User information
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsHost        bool                   `protobuf:"varint,3,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	IsConnected   bool                   `protobuf:"varint,4,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_listentogether_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

func (x *UserInfo) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

// Room state
type RoomState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Users         []*UserInfo            `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	CurrentTrack  *TrackInfo             `protobuf:"bytes,4,opt,name=current_track,json=currentTrack,proto3" json:"current_track,omitempty"`
	IsPlaying     bool                   `protobuf:"varint,5,opt,name=is_playing,json=isPlaying,proto3" json:"is_playing,omitempty"`
	Position      int64                  `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,7,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Volume        float32                `protobuf:"fixed32,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Queue         []*TrackInfo           `protobuf:"bytes,9,rep,name=queue,proto3" json:"queue,omitempty"`
	Revision      uint64                 `protobuf:"varint,10,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomState) Reset() {
	*x = RoomState{}
	mi := &file_listentogether_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState) ProtoMessage() {}

func (x *RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomState.ProtoReflect.Descriptor instead.
func (*RoomState) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{3}
}

func (x *RoomState) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomState) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RoomState) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *RoomState) GetCurrentTrack() *TrackInfo {
	if x != nil {
		return x.CurrentTrack
	}
	return nil
}

func (x *RoomState) GetIsPlaying() bool {
	if x != nil {
		return x.IsPlaying
	}
	return false
}

func (x *RoomState) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RoomState) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *RoomState) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *RoomState) GetQueue() []*TrackInfo {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *RoomState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CreateRoomPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomPayload) Reset() {
	*x = CreateRoomPayload{}
	mi := &file_listentogether_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomPayload) ProtoMessage() {}

func (x *CreateRoomPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomPayload.ProtoReflect.Descriptor instead.
func (*CreateRoomPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type JoinRoomPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomPayload) Reset() {
	*x = JoinRoomPayload{}
	mi := &file_listentogether_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomPayload) ProtoMessage() {}

func (x *JoinRoomPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomPayload.ProtoReflect.Descriptor instead.
func (*JoinRoomPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *JoinRoomPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LeaveRoomPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomPayload) Reset() {
	*x = LeaveRoomPayload{}
	mi := &file_listentogether_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomPayload) ProtoMessage() {}

func (x *LeaveRoomPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomPayload.ProtoReflect.Descriptor instead.
func (*LeaveRoomPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{6}
}

type ApproveJoinPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveJoinPayload) Reset() {
	*x = ApproveJoinPayload{}
	mi := &file_listentogether_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveJoinPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveJoinPayload) ProtoMessage() {}

func (x *ApproveJoinPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveJoinPayload.ProtoReflect.Descriptor instead.
func (*ApproveJoinPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{7}
}

func (x *ApproveJoinPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RejectJoinPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectJoinPayload) Reset() {
	*x = RejectJoinPayload{}
	mi := &file_listentogether_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectJoinPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectJoinPayload) ProtoMessage() {}

func (x *RejectJoinPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectJoinPayload.ProtoReflect.Descriptor instead.
func (*RejectJoinPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{8}
}

func (x *RejectJoinPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RejectJoinPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PlaybackActionPayload struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Action               string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	TrackId              string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Position             int64                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	TrackInfo            *TrackInfo             `protobuf:"bytes,4,opt,name=track_info,json=trackInfo,proto3" json:"track_info,omitempty"`
	InsertNext           bool                   `protobuf:"varint,5,opt,name=insert_next,json=insertNext,proto3" json:"insert_next,omitempty"`
	Queue                []*TrackInfo           `protobuf:"bytes,6,rep,name=queue,proto3" json:"queue,omitempty"`
	QueueTitle           string                 `protobuf:"bytes,7,opt,name=queue_title,json=queueTitle,proto3" json:"queue_title,omitempty"`
	Volume               float32                `protobuf:"fixed32,8,opt,name=volume,proto3" json:"volume,omitempty"`
	ServerTime           int64                  `protobuf:"varint,9,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Revision             uint64                 `protobuf:"varint,10,opt,name=revision,proto3" json:"revision,omitempty"`
	CapturedAtServerTime int64                  `protobuf:"varint,11,opt,name=captured_at_server_time,json=capturedAtServerTime,proto3" json:"captured_at_server_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlaybackActionPayload) Reset() {
	*x = PlaybackActionPayload{}
	mi := &file_listentogether_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackActionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackActionPayload) ProtoMessage() {}

func (x *PlaybackActionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackActionPayload.ProtoReflect.Descriptor instead.
func (*PlaybackActionPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{9}
}

func (x *PlaybackActionPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlaybackActionPayload) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *PlaybackActionPayload) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PlaybackActionPayload) GetTrackInfo() *TrackInfo {
	if x != nil {
		return x.TrackInfo
	}
	return nil
}

func (x *PlaybackActionPayload) GetInsertNext() bool {
	if x != nil {
		return x.InsertNext
	}
	return false
}

func (x *PlaybackActionPayload) GetQueue() []*TrackInfo {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *PlaybackActionPayload) GetQueueTitle() string {
	if x != nil {
		return x.QueueTitle
	}
	return ""
}

func (x *PlaybackActionPayload) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PlaybackActionPayload) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *PlaybackActionPayload) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *PlaybackActionPayload) GetCapturedAtServerTime() int64 {
	if x != nil {
		return x.CapturedAtServerTime
	}
	return 0
}

type PingPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingPayload) Reset() {
	*x = PingPayload{}
	mi := &file_listentogether_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPayload) ProtoMessage() {}

func (x *PingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPayload.ProtoReflect.Descriptor instead.
func (*PingPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{10}
}

func (x *PingPayload) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *PingPayload) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type BufferReadyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferReadyPayload) Reset() {
	*x = BufferReadyPayload{}
	mi := &file_listentogether_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferReadyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferReadyPayload) ProtoMessage() {}

func (x *BufferReadyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferReadyPayload.ProtoReflect.Descriptor instead.
func (*BufferReadyPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{11}
}

func (x *BufferReadyPayload) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type KickUserPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserPayload) Reset() {
	*x = KickUserPayload{}
	mi := &file_listentogether_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserPayload) ProtoMessage() {}

func (x *KickUserPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserPayload.ProtoReflect.Descriptor instead.
func (*KickUserPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{12}
}

func (x *KickUserPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KickUserPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TransferHostPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewHostId     string                 `protobuf:"bytes,1,opt,name=new_host_id,json=newHostId,proto3" json:"new_host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferHostPayload) Reset() {
	*x = TransferHostPayload{}
	mi := &file_listentogether_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferHostPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHostPayload) ProtoMessage() {}

func (x *TransferHostPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHostPayload.ProtoReflect.Descriptor instead.
func (*TransferHostPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{13}
}

func (x *TransferHostPayload) GetNewHostId() string {
	if x != nil {
		return x.NewHostId
	}
	return ""
}

type SuggestTrackPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackInfo     *TrackInfo             `protobuf:"bytes,1,opt,name=track_info,json=trackInfo,proto3" json:"track_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTrackPayload) Reset() {
	*x = SuggestTrackPayload{}
	mi := &file_listentogether_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTrackPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTrackPayload) ProtoMessage() {}

func (x *SuggestTrackPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTrackPayload.ProtoReflect.Descriptor instead.
func (*SuggestTrackPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{14}
}

func (x *SuggestTrackPayload) GetTrackInfo() *TrackInfo {
	if x != nil {
		return x.TrackInfo
	}
	return nil
}

type ApproveSuggestionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuggestionId  string                 `protobuf:"bytes,1,opt,name=suggestion_id,json=suggestionId,proto3" json:"suggestion_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveSuggestionPayload) Reset() {
	*x = ApproveSuggestionPayload{}
	mi := &file_listentogether_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveSuggestionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveSuggestionPayload) ProtoMessage() {}

func (x *ApproveSuggestionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveSuggestionPayload.ProtoReflect.Descriptor instead.
func (*ApproveSuggestionPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{15}
}

func (x *ApproveSuggestionPayload) GetSuggestionId() string {
	if x != nil {
		return x.SuggestionId
	}
	return ""
}

type RejectSuggestionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuggestionId  string                 `protobuf:"bytes,1,opt,name=suggestion_id,json=suggestionId,proto3" json:"suggestion_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectSuggestionPayload) Reset() {
	*x = RejectSuggestionPayload{}
	mi := &file_listentogether_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectSuggestionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectSuggestionPayload) ProtoMessage() {}

func (x *RejectSuggestionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectSuggestionPayload.ProtoReflect.Descriptor instead.
func (*RejectSuggestionPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{16}
}

func (x *RejectSuggestionPayload) GetSuggestionId() string {
	if x != nil {
		return x.SuggestionId
	}
	return ""
}

func (x *RejectSuggestionPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReconnectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectPayload) Reset() {
	*x = ReconnectPayload{}
	mi := &file_listentogether_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectPayload) ProtoMessage() {}

func (x *ReconnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectPayload.ProtoReflect.Descriptor instead.
func (*ReconnectPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{17}
}

func (x *ReconnectPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type RoomCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreatedPayload) Reset() {
	*x = RoomCreatedPayload{}
	mi := &file_listentogether_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreatedPayload) ProtoMessage() {}

func (x *RoomCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreatedPayload.ProtoReflect.Descriptor instead.
func (*RoomCreatedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{18}
}

func (x *RoomCreatedPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomCreatedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomCreatedPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type JoinRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequestPayload) Reset() {
	*x = JoinRequestPayload{}
	mi := &file_listentogether_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequestPayload) ProtoMessage() {}

func (x *JoinRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequestPayload.ProtoReflect.Descriptor instead.
func (*JoinRequestPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{19}
}

func (x *JoinRequestPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinRequestPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type JoinApprovedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	State         *RoomState             `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinApprovedPayload) Reset() {
	*x = JoinApprovedPayload{}
	mi := &file_listentogether_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinApprovedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinApprovedPayload) ProtoMessage() {}

func (x *JoinApprovedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinApprovedPayload.ProtoReflect.Descriptor instead.
func (*JoinApprovedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{20}
}

func (x *JoinApprovedPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *JoinApprovedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinApprovedPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *JoinApprovedPayload) GetState() *RoomState {
	if x != nil {
		return x.State
	}
	return nil
}

type JoinRejectedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRejectedPayload) Reset() {
	*x = JoinRejectedPayload{}
	mi := &file_listentogether_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRejectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRejectedPayload) ProtoMessage() {}

func (x *JoinRejectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRejectedPayload.ProtoReflect.Descriptor instead.
func (*JoinRejectedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{21}
}

func (x *JoinRejectedPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserJoinedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserJoinedPayload) Reset() {
	*x = UserJoinedPayload{}
	mi := &file_listentogether_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJoinedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinedPayload) ProtoMessage() {}

func (x *UserJoinedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinedPayload.ProtoReflect.Descriptor instead.
func (*UserJoinedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{22}
}

func (x *UserJoinedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserJoinedPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserLeftPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLeftPayload) Reset() {
	*x = UserLeftPayload{}
	mi := &file_listentogether_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLeftPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeftPayload) ProtoMessage() {}

func (x *UserLeftPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeftPayload.ProtoReflect.Descriptor instead.
func (*UserLeftPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{23}
}

func (x *UserLeftPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLeftPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BufferWaitPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	WaitingFor    []string               `protobuf:"bytes,2,rep,name=waiting_for,json=waitingFor,proto3" json:"waiting_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferWaitPayload) Reset() {
	*x = BufferWaitPayload{}
	mi := &file_listentogether_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferWaitPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferWaitPayload) ProtoMessage() {}

func (x *BufferWaitPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferWaitPayload.ProtoReflect.Descriptor instead.
func (*BufferWaitPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{24}
}

func (x *BufferWaitPayload) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *BufferWaitPayload) GetWaitingFor() []string {
	if x != nil {
		return x.WaitingFor
	}
	return nil
}

type BufferCompletePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferCompletePayload) Reset() {
	*x = BufferCompletePayload{}
	mi := &file_listentogether_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferCompletePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferCompletePayload) ProtoMessage() {}

func (x *BufferCompletePayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferCompletePayload.ProtoReflect.Descriptor instead.
func (*BufferCompletePayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{25}
}

func (x *BufferCompletePayload) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type ErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPayload) Reset() {
	*x = ErrorPayload{}
	mi := &file_listentogether_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPayload) ProtoMessage() {}

func (x *ErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPayload.ProtoReflect.Descriptor instead.
func (*ErrorPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{26}
}

func (x *ErrorPayload) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HostChangedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewHostId     string                 `protobuf:"bytes,1,opt,name=new_host_id,json=newHostId,proto3" json:"new_host_id,omitempty"`
	NewHostName   string                 `protobuf:"bytes,2,opt,name=new_host_name,json=newHostName,proto3" json:"new_host_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostChangedPayload) Reset() {
	*x = HostChangedPayload{}
	mi := &file_listentogether_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostChangedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostChangedPayload) ProtoMessage() {}

func (x *HostChangedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostChangedPayload.ProtoReflect.Descriptor instead.
func (*HostChangedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{27}
}

func (x *HostChangedPayload) GetNewHostId() string {
	if x != nil {
		return x.NewHostId
	}
	return ""
}

func (x *HostChangedPayload) GetNewHostName() string {
	if x != nil {
		return x.NewHostName
	}
	return ""
}

type KickedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickedPayload) Reset() {
	*x = KickedPayload{}
	mi := &file_listentogether_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickedPayload) ProtoMessage() {}

func (x *KickedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickedPayload.ProtoReflect.Descriptor instead.
func (*KickedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{28}
}

func (x *KickedPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SyncStatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTrack  *TrackInfo             `protobuf:"bytes,1,opt,name=current_track,json=currentTrack,proto3" json:"current_track,omitempty"`
	IsPlaying     bool                   `protobuf:"varint,2,opt,name=is_playing,json=isPlaying,proto3" json:"is_playing,omitempty"`
	Position      int64                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Queue         []*TrackInfo           `protobuf:"bytes,5,rep,name=queue,proto3" json:"queue,omitempty"`
	Volume        float32                `protobuf:"fixed32,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Revision      uint64                 `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStatePayload) Reset() {
	*x = SyncStatePayload{}
	mi := &file_listentogether_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatePayload) ProtoMessage() {}

func (x *SyncStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatePayload.ProtoReflect.Descriptor instead.
func (*SyncStatePayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{29}
}

func (x *SyncStatePayload) GetCurrentTrack() *TrackInfo {
	if x != nil {
		return x.CurrentTrack
	}
	return nil
}

func (x *SyncStatePayload) GetIsPlaying() bool {
	if x != nil {
		return x.IsPlaying
	}
	return false
}

func (x *SyncStatePayload) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *SyncStatePayload) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *SyncStatePayload) GetQueue() []*TrackInfo {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *SyncStatePayload) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *SyncStatePayload) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type PongPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientTime        int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	ServerReceiveTime int64                  `protobuf:"varint,2,opt,name=server_receive_time,json=serverReceiveTime,proto3" json:"server_receive_time,omitempty"`
	ServerSendTime    int64                  `protobuf:"varint,3,opt,name=server_send_time,json=serverSendTime,proto3" json:"server_send_time,omitempty"`
	Sequence          uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PongPayload) Reset() {
	*x = PongPayload{}
	mi := &file_listentogether_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongPayload) ProtoMessage() {}

func (x *PongPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongPayload.ProtoReflect.Descriptor instead.
func (*PongPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{30}
}

func (x *PongPayload) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *PongPayload) GetServerReceiveTime() int64 {
	if x != nil {
		return x.ServerReceiveTime
	}
	return 0
}

func (x *PongPayload) GetServerSendTime() int64 {
	if x != nil {
		return x.ServerSendTime
	}
	return 0
}

func (x *PongPayload) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ReconnectedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	State         *RoomState             `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	IsHost        bool                   `protobuf:"varint,4,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectedPayload) Reset() {
	*x = ReconnectedPayload{}
	mi := &file_listentogether_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectedPayload) ProtoMessage() {}

func (x *ReconnectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectedPayload.ProtoReflect.Descriptor instead.
func (*ReconnectedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{31}
}

func (x *ReconnectedPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *ReconnectedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReconnectedPayload) GetState() *RoomState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ReconnectedPayload) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

type UserReconnectedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReconnectedPayload) Reset() {
	*x = UserReconnectedPayload{}
	mi := &file_listentogether_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReconnectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReconnectedPayload) ProtoMessage() {}

func (x *UserReconnectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReconnectedPayload.ProtoReflect.Descriptor instead.
func (*UserReconnectedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{32}
}

func (x *UserReconnectedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserReconnectedPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserDisconnectedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDisconnectedPayload) Reset() {
	*x = UserDisconnectedPayload{}
	mi := &file_listentogether_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDisconnectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDisconnectedPayload) ProtoMessage() {}

func (x *UserDisconnectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDisconnectedPayload.ProtoReflect.Descriptor instead.
func (*UserDisconnectedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{33}
}

func (x *UserDisconnectedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDisconnectedPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SuggestionReceivedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuggestionId  string                 `protobuf:"bytes,1,opt,name=suggestion_id,json=suggestionId,proto3" json:"suggestion_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromUsername  string                 `protobuf:"bytes,3,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	TrackInfo     *TrackInfo             `protobuf:"bytes,4,opt,name=track_info,json=trackInfo,proto3" json:"track_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionReceivedPayload) Reset() {
	*x = SuggestionReceivedPayload{}
	mi := &file_listentogether_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionReceivedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionReceivedPayload) ProtoMessage() {}

func (x *SuggestionReceivedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionReceivedPayload.ProtoReflect.Descriptor instead.
func (*SuggestionReceivedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{34}
}

func (x *SuggestionReceivedPayload) GetSuggestionId() string {
	if x != nil {
		return x.SuggestionId
	}
	return ""
}

func (x *SuggestionReceivedPayload) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SuggestionReceivedPayload) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *SuggestionReceivedPayload) GetTrackInfo() *TrackInfo {
	if x != nil {
		return x.TrackInfo
	}
	return nil
}

type SuggestionApprovedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuggestionId  string                 `protobuf:"bytes,1,opt,name=suggestion_id,json=suggestionId,proto3" json:"suggestion_id,omitempty"`
	TrackInfo     *TrackInfo             `protobuf:"bytes,2,opt,name=track_info,json=trackInfo,proto3" json:"track_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionApprovedPayload) Reset() {
	*x = SuggestionApprovedPayload{}
	mi := &file_listentogether_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionApprovedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionApprovedPayload) ProtoMessage() {}

func (x *SuggestionApprovedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionApprovedPayload.ProtoReflect.Descriptor instead.
func (*SuggestionApprovedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{35}
}

func (x *SuggestionApprovedPayload) GetSuggestionId() string {
	if x != nil {
		return x.SuggestionId
	}
	return ""
}

func (x *SuggestionApprovedPayload) GetTrackInfo() *TrackInfo {
	if x != nil {
		return x.TrackInfo
	}
	return nil
}

type SuggestionRejectedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuggestionId  string                 `protobuf:"bytes,1,opt,name=suggestion_id,json=suggestionId,proto3" json:"suggestion_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionRejectedPayload) Reset() {
	*x = SuggestionRejectedPayload{}
	mi := &file_listentogether_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionRejectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionRejectedPayload) ProtoMessage() {}

func (x *SuggestionRejectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionRejectedPayload.ProtoReflect.Descriptor instead.
func (*SuggestionRejectedPayload) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{36}
}

func (x *SuggestionRejectedPayload) GetSuggestionId() string {
	if x != nil {
		return x.SuggestionId
	}
	return ""
}

func (x *SuggestionRejectedPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Capability negotiation (first message from client)
type ClientCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportsProtobuf    bool                   `protobuf:"varint,1,opt,name=supports_protobuf,json=supportsProtobuf,proto3" json:"supports_protobuf,omitempty"`
	SupportsCompression bool                   `protobuf:"varint,2,opt,name=supports_compression,json=supportsCompression,proto3" json:"supports_compression,omitempty"`
	ClientVersion       string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientCapabilities) Reset() {
	*x = ClientCapabilities{}
	mi := &file_listentogether_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCapabilities) ProtoMessage() {}

func (x *ClientCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCapabilities.ProtoReflect.Descriptor instead.
func (*ClientCapabilities) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{37}
}

func (x *ClientCapabilities) GetSupportsProtobuf() bool {
	if x != nil {
		return x.SupportsProtobuf
	}
	return false
}

func (x *ClientCapabilities) GetSupportsCompression() bool {
	if x != nil {
		return x.SupportsCompression
	}
	return false
}

func (x *ClientCapabilities) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type ServerCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportsProtobuf    bool                   `protobuf:"varint,1,opt,name=supports_protobuf,json=supportsProtobuf,proto3" json:"supports_protobuf,omitempty"`
	SupportsCompression bool                   `protobuf:"varint,2,opt,name=supports_compression,json=supportsCompression,proto3" json:"supports_compression,omitempty"`
	ServerVersion       string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerCapabilities) Reset() {
	*x = ServerCapabilities{}
	mi := &file_listentogether_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCapabilities) ProtoMessage() {}

func (x *ServerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_listentogether_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCapabilities.ProtoReflect.Descriptor instead.
func (*ServerCapabilities) Descriptor() ([]byte, []int) {
	return file_listentogether_proto_rawDescGZIP(), []int{38}
}

func (x *ServerCapabilities) GetSupportsProtobuf() bool {
	if x != nil {
		return x.SupportsProtobuf
	}
	return false
}

func (x *ServerCapabilities) GetSupportsCompression() bool {
	if x != nil {
		return x.SupportsCompression
	}
	return false
}

func (x *ServerCapabilities) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

var File_listentogether_proto protoreflect.FileDescriptor

const file_listentogether_proto_rawDesc = "" +
	"\n" +
	"\x14listentogether.proto\x12\x0elistentogether\"X\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1e\n" +
	"\n" +
	"compressed\x18\x03 \x01(\bR\n" +
	"compressed\"\xbc\x01\n" +
	"\tTrackInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x12\x1c\n" +
	"\tthumbnail\x18\x06 \x01(\tR\tthumbnail\x12!\n" +
	"\fsuggested_by\x18\a \x01(\tR\vsuggestedBy\"{\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x17\n" +
	"\ais_host\x18\x03 \x01(\bR\x06isHost\x12!\n" +
	"\fis_connected\x18\x04 \x01(\bR\visConnected\"\xf2\x02\n" +
	"\tRoomState\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12.\n" +
	"\x05users\x18\x03 \x03(\v2\x18.listentogether.UserInfoR\x05users\x12>\n" +
	"\rcurrent_track\x18\x04 \x01(\v2\x19.listentogether.TrackInfoR\fcurrentTrack\x12\x1d\n" +
	"\n" +
	"is_playing\x18\x05 \x01(\bR\tisPlaying\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x03R\bposition\x12\x1f\n" +
	"\vlast_update\x18\a \x01(\x03R\n" +
	"lastUpdate\x12\x16\n" +
	"\x06volume\x18\b \x01(\x02R\x06volume\x12/\n" +
	"\x05queue\x18\t \x03(\v2\x19.listentogether.TrackInfoR\x05queue\x12\x1a\n" +
	"\brevision\x18\n" +
	" \x01(\x04R\brevision\"/\n" +
	"\x11CreateRoomPayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"J\n" +
	"\x0fJoinRoomPayload\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x12\n" +
	"\x10LeaveRoomPayload\"-\n" +
	"\x12ApproveJoinPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x11RejectJoinPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x9f\x03\n" +
	"\x15PlaybackActionPayload\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\x128\n" +
	"\n" +
	"track_info\x18\x04 \x01(\v2\x19.listentogether.TrackInfoR\ttrackInfo\x12\x1f\n" +
	"\vinsert_next\x18\x05 \x01(\bR\n" +
	"insertNext\x12/\n" +
	"\x05queue\x18\x06 \x03(\v2\x19.listentogether.TrackInfoR\x05queue\x12\x1f\n" +
	"\vqueue_title\x18\a \x01(\tR\n" +
	"queueTitle\x12\x16\n" +
	"\x06volume\x18\b \x01(\x02R\x06volume\x12\x1f\n" +
	"\vserver_time\x18\t \x01(\x03R\n" +
	"serverTime\x12\x1a\n" +
	"\brevision\x18\n" +
	" \x01(\x04R\brevision\x125\n" +
	"\x17captured_at_server_time\x18\v \x01(\x03R\x14capturedAtServerTime\"J\n" +
	"\vPingPayload\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"/\n" +
	"\x12BufferReadyPayload\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\"B\n" +
	"\x0fKickUserPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"5\n" +
	"\x13TransferHostPayload\x12\x1e\n" +
	"\vnew_host_id\x18\x01 \x01(\tR\tnewHostId\"O\n" +
	"\x13SuggestTrackPayload\x128\n" +
	"\n" +
	"track_info\x18\x01 \x01(\v2\x19.listentogether.TrackInfoR\ttrackInfo\"?\n" +
	"\x18ApproveSuggestionPayload\x12#\n" +
	"\rsuggestion_id\x18\x01 \x01(\tR\fsuggestionId\"V\n" +
	"\x17RejectSuggestionPayload\x12#\n" +
	"\rsuggestion_id\x18\x01 \x01(\tR\fsuggestionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"7\n" +
	"\x10ReconnectPayload\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"o\n" +
	"\x12RoomCreatedPayload\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"I\n" +
	"\x12JoinRequestPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xa1\x01\n" +
	"\x13JoinApprovedPayload\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12/\n" +
	"\x05state\x18\x04 \x01(\v2\x19.listentogether.RoomStateR\x05state\"-\n" +
	"\x13JoinRejectedPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"H\n" +
	"\x11UserJoinedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"F\n" +
	"\x0fUserLeftPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"O\n" +
	"\x11BufferWaitPayload\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x1f\n" +
	"\vwaiting_for\x18\x02 \x03(\tR\n" +
	"waitingFor\"2\n" +
	"\x15BufferCompletePayload\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\"<\n" +
	"\fErrorPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"X\n" +
	"\x12HostChangedPayload\x12\x1e\n" +
	"\vnew_host_id\x18\x01 \x01(\tR\tnewHostId\x12\"\n" +
	"\rnew_host_name\x18\x02 \x01(\tR\vnewHostName\"'\n" +
	"\rKickedPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x93\x02\n" +
	"\x10SyncStatePayload\x12>\n" +
	"\rcurrent_track\x18\x01 \x01(\v2\x19.listentogether.TrackInfoR\fcurrentTrack\x12\x1d\n" +
	"\n" +
	"is_playing\x18\x02 \x01(\bR\tisPlaying\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\x12\x1f\n" +
	"\vlast_update\x18\x04 \x01(\x03R\n" +
	"lastUpdate\x12/\n" +
	"\x05queue\x18\x05 \x03(\v2\x19.listentogether.TrackInfoR\x05queue\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x02R\x06volume\x12\x1a\n" +
	"\brevision\x18\a \x01(\x04R\brevision\"\xa4\x01\n" +
	"\vPongPayload\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\x12.\n" +
	"\x13server_receive_time\x18\x02 \x01(\x03R\x11serverReceiveTime\x12(\n" +
	"\x10server_send_time\x18\x03 \x01(\x03R\x0eserverSendTime\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\"\x94\x01\n" +
	"\x12ReconnectedPayload\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12/\n" +
	"\x05state\x18\x03 \x01(\v2\x19.listentogether.RoomStateR\x05state\x12\x17\n" +
	"\ais_host\x18\x04 \x01(\bR\x06isHost\"M\n" +
	"\x16UserReconnectedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"N\n" +
	"\x17UserDisconnectedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xc1\x01\n" +
	"\x19SuggestionReceivedPayload\x12#\n" +
	"\rsuggestion_id\x18\x01 \x01(\tR\fsuggestionId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12#\n" +
	"\rfrom_username\x18\x03 \x01(\tR\ffromUsername\x128\n" +
	"\n" +
	"track_info\x18\x04 \x01(\v2\x19.listentogether.TrackInfoR\ttrackInfo\"z\n" +
	"\x19SuggestionApprovedPayload\x12#\n" +
	"\rsuggestion_id\x18\x01 \x01(\tR\fsuggestionId\x128\n" +
	"\n" +
	"track_info\x18\x02 \x01(\v2\x19.listentogether.TrackInfoR\ttrackInfo\"X\n" +
	"\x19SuggestionRejectedPayload\x12#\n" +
	"\rsuggestion_id\x18\x01 \x01(\tR\fsuggestionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x9b\x01\n" +
	"\x12ClientCapabilities\x12+\n" +
	"\x11supports_protobuf\x18\x01 \x01(\bR\x10supportsProtobuf\x121\n" +
	"\x14supports_compression\x18\x02 \x01(\bR\x13supportsCompression\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\"\x9b\x01\n" +
	"\x12ServerCapabilities\x12+\n" +
	"\x11supports_protobuf\x18\x01 \x01(\bR\x10supportsProtobuf\x121\n" +
	"\x14supports_compression\x18\x02 \x01(\bR\x13supportsCompression\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersionBi\n" +
	"(com.metrolist.music.listentogether.protoB\x0eListentogetherP\x00Z+github.com/MetrolistGroup/metroserver/protob\x06proto3"

var (
	file_listentogether_proto_rawDescOnce sync.Once
	file_listentogether_proto_rawDescData []byte
)

func file_listentogether_proto_rawDescGZIP() []byte {
	file_listentogether_proto_rawDescOnce.Do(func() {
		file_listentogether_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listentogether_proto_rawDesc), len(file_listentogether_proto_rawDesc)))
	})
	return file_listentogether_proto_rawDescData
}

var file_listentogether_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_listentogether_proto_goTypes = []any{
	(*Envelope)(nil),                  // 0: listentogether.Envelope
	(*TrackInfo)(nil),                 // 1: listentogether.TrackInfo
	(*UserInfo)(nil),                  // 2: listentogether.UserInfo
	(*RoomState)(nil),                 // 3: listentogether.RoomState
	(*CreateRoomPayload)(nil),         // 4: listentogether.CreateRoomPayload
	(*JoinRoomPayload)(nil),           // 5: listentogether.JoinRoomPayload
	(*LeaveRoomPayload)(nil),          // 6: listentogether.LeaveRoomPayload
	(*ApproveJoinPayload)(nil),        // 7: listentogether.ApproveJoinPayload
	(*RejectJoinPayload)(nil),         // 8: listentogether.RejectJoinPayload
	(*PlaybackActionPayload)(nil),     // 9: listentogether.PlaybackActionPayload
	(*PingPayload)(nil),               // 10: listentogether.PingPayload
	(*BufferReadyPayload)(nil),        // 11: listentogether.BufferReadyPayload
	(*KickUserPayload)(nil),           // 12: listentogether.KickUserPayload
	(*TransferHostPayload)(nil),       // 13: listentogether.TransferHostPayload
	(*SuggestTrackPayload)(nil),       // 14: listentogether.SuggestTrackPayload
	(*ApproveSuggestionPayload)(nil),  // 15: listentogether.ApproveSuggestionPayload
	(*RejectSuggestionPayload)(nil),   // 16: listentogether.RejectSuggestionPayload
	(*ReconnectPayload)(nil),          // 17: listentogether.ReconnectPayload
	(*RoomCreatedPayload)(nil),        // 18: listentogether.RoomCreatedPayload
	(*JoinRequestPayload)(nil),        // 19: listentogether.JoinRequestPayload
	(*JoinApprovedPayload)(nil),       // 20: listentogether.JoinApprovedPayload
	(*JoinRejectedPayload)(nil),       // 21: listentogether.JoinRejectedPayload
	(*UserJoinedPayload)(nil),         // 22: listentogether.UserJoinedPayload
	(*UserLeftPayload)(nil),           // 23: listentogether.UserLeftPayload
	(*BufferWaitPayload)(nil),         // 24: listentogether.BufferWaitPayload
	(*BufferCompletePayload)(nil),     // 25: listentogether.BufferCompletePayload
	(*ErrorPayload)(nil),              // 26: listentogether.ErrorPayload
	(*HostChangedPayload)(nil),        // 27: listentogether.HostChangedPayload
	(*KickedPayload)(nil),             // 28: listentogether.KickedPayload
	(*SyncStatePayload)(nil),          // 29: listentogether.SyncStatePayload
	(*PongPayload)(nil),               // 30: listentogether.PongPayload
	(*ReconnectedPayload)(nil),        // 31: listentogether.ReconnectedPayload
	(*UserReconnectedPayload)(nil),    // 32: listentogether.UserReconnectedPayload
	(*UserDisconnectedPayload)(nil),   // 33: listentogether.UserDisconnectedPayload
	(*SuggestionReceivedPayload)(nil), // 34: listentogether.SuggestionReceivedPayload
	(*SuggestionApprovedPayload)(nil), // 35: listentogether.SuggestionApprovedPayload
	(*SuggestionRejectedPayload)(nil), // 36: listentogether.SuggestionRejectedPayload
	(*ClientCapabilities)(nil),        // 37: listentogether.ClientCapabilities
	(*ServerCapabilities)(nil),        // 38: listentogether.ServerCapabilities
}
var file_listentogether_proto_depIdxs = []int32{
	2,  // 0: listentogether.RoomState.users:type_name -> listentogether.UserInfo
	1,  // 1: listentogether.RoomState.current_track:type_name -> listentogether.TrackInfo
	1,  // 2: listentogether.RoomState.queue:type_name -> listentogether.TrackInfo
	1,  // 3: listentogether.PlaybackActionPayload.track_info:type_name -> listentogether.TrackInfo
	1,  // 4: listentogether.PlaybackActionPayload.queue:type_name -> listentogether.TrackInfo
	1,  // 5: listentogether.SuggestTrackPayload.track_info:type_name -> listentogether.TrackInfo
	3,  // 6: listentogether.JoinApprovedPayload.state:type_name -> listentogether.RoomState
	1,  // 7: listentogether.SyncStatePayload.current_track:type_name -> listentogether.TrackInfo
	1,  // 8: listentogether.SyncStatePayload.queue:type_name -> listentogether.TrackInfo
	3,  // 9: listentogether.ReconnectedPayload.state:type_name -> listentogether.RoomState
	1,  // 10: listentogether.SuggestionReceivedPayload.track_info:type_name -> listentogether.TrackInfo
	1,  // 11: listentogether.SuggestionApprovedPayload.track_info:type_name -> listentogether.TrackInfo
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_listentogether_proto_init() }
func file_listentogether_proto_init() {
	if File_listentogether_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listentogether_proto_rawDesc), len(file_listentogether_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listentogether_proto_goTypes,
		DependencyIndexes: file_listentogether_proto_depIdxs,
		MessageInfos:      file_listentogether_proto_msgTypes,
	}.Build()
	File_listentogether_proto = out.File
	file_listentogether_proto_goTypes = nil
	file_listentogether_proto_depIdxs = nil
}
